from django.db import models
from django.utils import timezone

class Roadmap(models.Model):
    interviewer = models.CharField(max_length=100)
    topic = models.CharField(max_length=100)
    llm_response = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

class Topic(models.Model):
    roadmap = models.ForeignKey(Roadmap, related_name='topics', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    importance_score = models.FloatField()
    # Optionally, you can add more fields as needed

class Subtopic(models.Model):
    topic = models.ForeignKey(Topic, related_name='subtopics', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)

class ChatMessage(models.Model):
    """
    Stores individual chat messages between the user and the LLM.
    Each message is linked to a specific subtopic.
    """
    id = models.AutoField(primary_key=True)
    subtopic = models.ForeignKey(Subtopic, on_delete=models.CASCADE, related_name='chat_messages', help_text="The subtopic this chat message belongs to.")
    user_message = models.TextField(help_text="The message sent by the user.")
    llm_response = models.TextField(blank=True, null=True, help_text="The response generated by the LLM.")
    timestamp = models.DateTimeField(default=timezone.now, help_text="The time the message was created.")

    class Meta:
        ordering = ['timestamp'] # Order chat messages chronologically
